import = [

	  "~/.config/alacritty/catppuccin-mocha.toml"
	  ]

[font]
normal = {family = "JetBrainsMono Nerd Font",style = "Regular"}

bold = {family = "JetBrainsMono Nerd Font",style = "Regular"}

italic = {family = "JetBrainsMono Nerd Font",style = "Regular"}
bold_italic = {family = "JetBrainsMono Nerd Font",style = "Regular"}
size = 7
